name: 'Pipeline'
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  ci:
    name: 'CI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run check
